#!/usr/bin/env bash
# Production-parity local run: build the real images, boot them against a
# local Postgres with prod-shaped env, migrate + seed, then smoke-test.
# Idempotent — safe to re-run anytime; `pnpm local-prod:down` tears it down.
set -euo pipefail

cd "$(dirname "$0")/.."

step() { printf "\n\033[1;34m▸ %s\033[0m\n" "$1"; }

COMPOSE="docker compose -f docker-compose.local-prod.yml"
# Host-side URL for migrate/seed; inside the compose network the apps use
# postgres:5432 (see .env.local-prod).
LOCAL_PROD_DB_URL="postgres://plinth:plinth@localhost:5434/plinth"

step "checking prerequisites"
command -v docker >/dev/null || { echo "docker is required: https://docs.docker.com/get-docker/"; exit 1; }
docker info >/dev/null 2>&1 || { echo "docker daemon is not running"; exit 1; }
command -v pnpm >/dev/null || { echo "pnpm is required: https://pnpm.io/installation"; exit 1; }
command -v openssl >/dev/null || { echo "openssl is required to generate local secrets"; exit 1; }

step "preparing .env.local-prod"
if [ ! -f .env.local-prod ]; then
  cat > .env.local-prod <<EOF
# Generated by scripts/local-prod.sh — prod-shaped env for the local-prod
# stack (the runtime contract validates these for real, exactly like Fly
# secrets in production). Hostnames are compose service names. Gitignored;
# delete the file to regenerate fresh secrets.
DATABASE_URL=postgres://plinth:plinth@postgres:5432/plinth
BETTER_AUTH_URL=http://localhost:3000
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
INTERNAL_API_URL=http://api:4000
INTERNAL_API_HMAC_SECRET=$(openssl rand -base64 32)
# Publish pipeline (ADR-0003): the env contract requires these at boot. The
# local-prod stack has no MinIO/Inngest services yet and the prod api image
# cannot run the astro builder (ADR-0013) — publish here queues and fails;
# use \`pnpm dev\` to exercise the full pipeline until the parity work lands.
INNGEST_DEV=1
R2_ENDPOINT_URL=http://minio:9000
R2_ACCESS_KEY_ID=plinth
R2_SECRET_ACCESS_KEY=plinth-local-dev
R2_BUCKET_SITES=plinth-sites
EOF
  echo "created .env.local-prod with generated secrets"
else
  echo ".env.local-prod already exists — leaving your values untouched"
fi

step "building production images (the same Dockerfiles the Fly deploys ship)"
$COMPOSE build

step "starting postgres"
$COMPOSE up -d --wait postgres

step "migrations + seed (same drizzle-kit path the deploy lane runs)"
DATABASE_URL="$LOCAL_PROD_DB_URL" pnpm --filter @plinth/db db:migrate
DATABASE_URL="$LOCAL_PROD_DB_URL" pnpm seed

step "starting the apps (runtime env validation is live — no SKIP_ENV_VALIDATION)"
$COMPOSE up -d --wait api dashboard

step "smoke tests"
./scripts/smoke.sh

step "done"
cat <<'EOF'

  Production-parity stack is up:
    Dashboard   http://localhost:3000
    Api         http://localhost:4000
    Postgres    postgres://plinth:plinth@localhost:5434/plinth

  Sign in as dev@plinth.local — the magic-link URL prints to the dashboard
  container logs:
    docker compose -f docker-compose.local-prod.yml logs -f dashboard

  Stop everything:
    pnpm local-prod:down

  Note: the apps bind :3000/:4000, same as `pnpm dev` — run one mode at a time.

EOF
