import { mediaVariantWidths, type MediaVariantFormat } from "@plinth/schema/api";
import sharp from "sharp";

/**
 * Sharp encoding for the media pipeline (ADR-0006) — pure, so it runs without
 * the adapter's env/S3 baggage, the same reason `./sniff` sits apart. That
 * matters beyond testing: the example-content fixture the tenant quality gates
 * build against is generated by this exact function, so committed fixture
 * bytes cannot drift from what a real upload produces.
 */

export interface ImageVariant {
  width: number;
  format: MediaVariantFormat;
  bytes: Buffer;
}

export interface ProcessedImage {
  width: number;
  height: number;
  variants: ImageVariant[];
}

/**
 * Decode once, emit AVIF + WebP + JPEG at every width that exists for the
 * original (never upscaled — `mediaVariantWidths` is the shared rule the
 * renderer's srcset derives from). `.rotate()` bakes EXIF orientation in, so
 * stored dimensions match what the browser will lay out.
 */
export async function processImage(input: Buffer): Promise<ProcessedImage> {
  const oriented = sharp(input).rotate();
  const meta = await oriented.toBuffer({ resolveWithObject: true });
  const { width, height } = meta.info;

  const widths = mediaVariantWidths(width);
  const variants = await Promise.all(
    widths.flatMap((targetWidth) => [
      encode(meta.data, targetWidth, "avif"),
      encode(meta.data, targetWidth, "webp"),
      encode(meta.data, targetWidth, "jpeg"),
    ]),
  );
  return { width, height, variants };
}

async function encode(
  input: Buffer,
  width: number,
  format: MediaVariantFormat,
): Promise<ImageVariant> {
  const resized = sharp(input).resize({ width, withoutEnlargement: true });
  const encoded =
    format === "avif"
      ? resized.avif({ quality: 60 })
      : format === "webp"
        ? resized.webp({ quality: 78 })
        : resized.jpeg({ quality: 80, mozjpeg: true });
  return { width, format, bytes: await encoded.toBuffer() };
}
